### ISSUE TITLE
What are you doing with the ynab api?

### ISSUE THREAD

**Issue by trashbirdecology** [jhollist/ynabr#1]
We use ynab gui + webapp -- curious what you're up to!

**Comment by jhollist** [comment]
Was going to write a package to access the API so I could pull in our data (we just started using it in December) and generate my own reports. metrics, etc.

That being said, after I got started I did notice https://github.com/mathewroy/ynabr which appears to be functional (unlike mine at this point).  I hope to give it a try in a week or so.

**Comment by jhollist** [comment]
Also, I haven't signed up yet for my years subscription.  If you want, send me your referral code and I'd be happy to use it!

**Comment by trashbirdecology** [comment]
Sweet.

**Comment by trashbirdecology** [comment]
oh, sweet!

https://ynab.com/referral/?ref=B0LJgFMlrYXiIJfL&utm_source=customer_referral

looks like we will both just get a free month

*______________________________________________________*

Jessica L. Burnett (she/her)

Mendenhall Postdoctoral Fellow & Research Ecologist

US Geological Survey Science Analytics and Synthesis
<https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis>

Github <http://github.com/trashbirdecology>

ORCID: 0000-0002-0896-5099
<https://orcid.org/0000-0002-0896-5099>
*______________________________________________________*


Join the Community for Data <https://www.usgs.gov/centers/cdi>! All welcome.

**Comment by jhollist** [comment]
Jessica,  Trying to work through this referral link thing and the YNAB help tells me they need the email that you use with YNAB to make the appropriate connection.  You OK sharing that?

**Comment by trashbirdecology** [comment]
Sure, jessicaleighburnett at gmail
